server:
  ip: 127.0.0.1
  port: 8888

mysql:
  ip: 127.0.0.1
  user: root
  password: '123456'
  database: robot

workshop: E

timeStamp:
  hour_20: num1
  hour_21: num2
  hour_22: num3
  hour_23: num4
  hour_0: num5
  hour_1: num6
  hour_2: num7
  hour_3: num8
  hour_4: num9
  hour_5: num10
  hour_6: num11
  hour_7: num12

  hour_8: num1
  hour_9: num2
  hour_10: num3
  hour_11: num4
  hour_12: num5
  hour_13: num6
  hour_14: num7
  hour_15: num8
  hour_16: num9
  hour_17: num10
  hour_18: num11
  hour_19: num12



devices:
  xe_line1_robot1:
    ip: 192.168.10.1
    serial: 'xe_line1_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 0
    firmWareVersion: 1

  xe_line1_robot2:
    ip: 192.168.10.1
    serial: 'xe_line1_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line1_robot3:
    ip: 192.168.10.1
    serial: 'xe_line1_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line1_ultra:
    ip: 192.168.10.1
    serial: 'xe_line1_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line2_robot1:
    ip: 192.168.10.1
    serial: 'xe_line2_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line2_robot2:
    ip: 192.168.10.1
    serial: 'xe_line2_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line2_robot3:
    ip: 192.168.10.1
    serial: 'xe_line2_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line2_ultra:
    ip: 192.168.10.1
    serial: 'xe_line2_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line3_robot1:
    ip: 192.168.10.1
    serial: 'xe_line3_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line3_robot2:
    ip: 192.168.10.1
    serial: 'xe_line3_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line3_robot3:
    ip: 192.168.10.1
    serial: 'xe_line3_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line3_ultra:
    ip: 192.168.10.1
    serial: 'xe_line3_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line4_robot1:
    ip: 192.168.10.1
    serial: 'xe_line4_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line4_robot2:
    ip: 192.168.10.1
    serial: 'xe_line4_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line4_robot3:
    ip: 192.168.10.1
    serial: 'xe_line4_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line4_ultra:
    ip: 192.168.10.1
    serial: 'xe_line4_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line5_robot1:
    ip: 192.168.10.1
    serial: 'xe_line5_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line5_robot2:
    ip: 192.168.10.1
    serial: 'xe_line5_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line5_robot3:
    ip: 192.168.10.1
    serial: 'xe_line5_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line5_ultra:
    ip: 192.168.10.1
    serial: 'xe_line5_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line6_robot1:
    ip: 192.168.10.1
    serial: 'xe_line6_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line6_robot2:
    ip: 192.168.10.1
    serial: 'xe_line6_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line6_robot3:
    ip: 192.168.10.1
    serial: 'xe_line6_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line6_ultra:
    ip: 192.168.10.1
    serial: 'xe_line6_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line7_robot1:
    ip: 192.168.10.1
    serial: 'xe_line7_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line7_robot2:
    ip: 192.168.10.1
    serial: 'xe_line7_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line7_robot3:
    ip: 192.168.10.1
    serial: 'xe_line7_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line7_ultra:
    ip: 192.168.10.1
    serial: 'xe_line7_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line8_robot1:
    ip: 192.168.10.1
    serial: 'xe_line8_robot1'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line8_robot2:
    ip: 192.168.10.1
    serial: 'xe_line8_robot2'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

  xe_line8_robot3:
    ip: 192.168.10.1
    serial: 'xe_line8_robot3'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1
    
  xe_line8_ultra:
    ip: 192.168.10.1
    serial: 'xe_line8_ultra'
    macAddress: 'mac test'
    productModel: 'product model test'
    productNum: 12
    firmWareVersion: 1

